"""Per-domain visual-reasoning guidance, selected by storyboard domain tags.

Previously every scene received one ~5,200-token block covering every maths and
physics topic at once. Flash-Lite has ample context for that, so this is not a
capacity fix — it is an *instruction-dilution* fix: a calculus scene that also
reads magnetism, optics and astrophysics rules follows its own rules less
consistently and drifts toward generic diagrams.

Each module below is the concise, animation-relevant slice for one tag in
:data:`schemas.DOMAIN_TAGS`. Modules state visual opportunities and correctness
constraints; they never prescribe a fixed diagram or a scene template.

Every Manim construct referenced here was render-verified in this environment
(Manim CE 0.19.1, cairo, no LaTeX) before being written down — notably the
cobweb/staircase iteration diagram, ``Cross(Circle(...))`` for into-page field
symbols, ``Angle`` / ``RightAngle`` marks, and ``Polygon`` trapezia. The
``BarChart`` class is excluded on purpose: its ``__init__`` builds ``Tex``
labels and therefore requires a LaTeX binary that is not installed.
"""

from __future__ import annotations

from typing import Iterable, List, Optional, Sequence

from schemas import DOMAIN_TAGS, MAX_TOTAL_DOMAIN_TAGS

# --------------------------------------------------------------------------- #
# Correctness preamble — always sent with ANY specialist module (but not with a
# bare "general" scene, which has no domain claims to get wrong).
# --------------------------------------------------------------------------- #
_DOMAIN_HEADER = """DOMAIN VISUAL REASONING (guidance for THIS scene's subject — not a template.
Infer the right metaphor from the scene's objective; never force a listed
technique into a scene that does not need it):"""

_ACCURACY_RULE = """ACCURACY: every arrow, field line, particle, axis, rotation and trajectory must
represent a REAL relationship, never decoration. A metaphor must not imply a
false claim. If you cannot say what a mark means, do not draw it."""


# --------------------------------------------------------------------------- #
# MATHEMATICS modules
# --------------------------------------------------------------------------- #

_ALGEBRA = """ALGEBRA, FUNCTIONS & SEQUENCES
- Derivations: keep aligned expressions with a STABLE colour per term and
  TransformFromCopy one line into the next, so a term visibly becomes its
  successor. Never cut to a disconnected new text slide.
- Graph transformations: Transform one axes.plot(f) directly into axes.plot(g)
  so the curve visibly SLIDES, STRETCHES or FLIPS — the clearest way to show
  f(x)+a, f(x-a), a*f(x), -f(x), f(-x).
- Exponentials & logarithms: plot growth/decay and mark equal-width steps along
  x with get_vertical_line so the constant doubling/halving ratio is VISIBLE
  rather than asserted; a half-life or doubling time is one such interval. A
  logarithm is the inverse — reflect the exponential in the line y=x. For
  log-linearisation, Transform the curved plot into a straight Line on
  relabelled axes; the straightening IS the insight.
- Asymptotes: draw them as thin DashedLine objects BEFORE the curve, then
  Create the curve approaching without touching. Mark excluded points with a
  hollow Dot (a small Circle, no fill); show domain/range as highlighted
  intervals along the axes.
- Sequences & series: terms as a row of dots/bars arriving one at a time
  (LaggedStart) — spreading for a divergent sequence, settling toward a fixed
  value for a convergent one. A partial sum as a growing bar or a staircase of
  stacked rectangles. A recurrence must build each term FROM the previous one
  (TransformFromCopy), never independently."""

_GEOMETRY = """GEOMETRY, COORDINATE GEOMETRY & TRIGONOMETRY
- Coordinate geometry: a line as axes.plot(linear fn) or a Line between two
  axes.c2p(...) points, with a "rise over run" right-triangle built from two
  short Lines to show gradient; a circle via Circle(radius=..) centred with
  axes.c2p; a tangent as a Line touching at exactly one point (check visually
  that it does not cross).
- Trigonometry — THE SWEEP (the defining trig animation; reach for it whenever
  the link between angle and ratio is the point). ONE ValueTracker holds the
  angle and drives everything at once: the radius Line on a unit circle, a
  dashed PROJECTION line from the point on the circle to the horizontal axis,
  and the matching point on the sin/cos curve on Axes beside it. The curve is
  GENERATED by the sweep, not traced over a curve that already exists — either
  redraw a partial plot, axes.plot(f, x_range=[0, t.get_value()]), or put
  Create(curve) in the SAME self.play(...) as the tracker so both run on one
  clock. NOTE: the general "use Rotate sparingly" caution does NOT apply here —
  in trigonometry the angle IS the variable, so a full continuous sweep is the
  content, not decoration.
  Say what the projection MEANS, because students are rarely shown it: the
  vertical drop from the circle point to the axis IS sin θ, and the horizontal
  offset IS cos θ. The sine is a projection, not a number from a table.
- Why trig works at all — SCALE INVARIANCE: one tracker on a scale factor grows
  and shrinks a right triangle while the ratio opp/hyp stays FIXED. The triangle
  visibly changes size; the ratio does not. This answers "why does a ratio
  depend only on the angle?", which a static diagram cannot.
- Solving trig equations IN AN INTERVAL (the most-missed A-level skill — students
  find one solution and stop): draw y = k as a horizontal DashedLine across the
  curve over the whole stated range, then Dot EVERY intersection (LaggedStart)
  and drop a line from each to the x-axis. Map the solutions back to the unit
  circle / CAST quadrants so the viewer sees WHY there is more than one. Never
  show only the principal value.
- The Pythagorean identity is not a fact to memorise, it is Pythagoras: on the
  unit circle, the cos leg, the sin leg and the radius form a right triangle
  with hypotenuse 1, so sin²θ + cos²θ = 1 falls straight out. Mark the right
  angle (RightAngle) and colour each leg to match its label.
- Sine rule: a genuine non-right triangle as a Polygon, sides and angles marked
  (Angle arcs), with each related side-angle PAIR sharing a colour — the
  pairing is the entire content of the sine rule.
- Cosine rule is about the INCLUDED angle between the two known sides, not
  about pairs — highlight that angle specifically. The strongest way to show it
  is as a GENERALISED PYTHAGORAS: hold two sides fixed, sweep the included
  angle toward 90° with a ValueTracker, and let the −2ab·cos C term visibly
  shrink to nothing, leaving c² = a² + b². The two "rules" are then one rule,
  which is far more memorable than two formulas to look up.
- CHOOSING WHICH RULE is the actual exam skill, so make the choice VISIBLE
  rather than announcing it: light up what is known on the triangle and dim the
  rest. If a complete side-and-its-opposite-angle PAIR is lit, the sine rule is
  available; if instead two sides and the angle BETWEEN them are lit (or all
  three sides), it is the cosine rule. The lit quantities should select the
  rule on screen before its name appears.
- Bearings (for real-world distance/navigation problems): draw the NORTH arrow
  first, measure the bearing CLOCKWISE from north, and write it as three
  figures (065°, not 65°). A bearing drawn anticlockwise, or from another
  reference direction, is a convention error — treat it as seriously as a
  reversed force arrow.
- Modelling a real situation: when a scene starts from a real context (two
  towns, a ship, a surveyor), show the ABSTRACTION happening — the real objects
  fade back and dim while the triangle is drawn over them and comes forward
  (set_z_index + opacity, the flat -> layered lift). Keeping the context dimly
  behind the triangle is what stops it becoming "just a maths diagram".
- CAST / quadrant sign work: shade the relevant unit-circle quadrant (Sector)
  and show the sign of each ratio there.
- RENDER COST (measured here, 480p15 — a sweep scene is easy to make 10x slower
  than it needs to be): reactive GEOMETRY is cheap (~5s for several
  always_redraw shapes over a 3s sweep), but a Text rebuilt every frame via
  always_redraw costs ~3x MORE THAN THE ENTIRE REST OF THE SCENE. Prefer to let
  the geometry carry the value — the projection line's length IS sin θ — with a
  couple of STATIC labels. If a changing number is genuinely the point, update it
  a few times rather than every frame. Build all of one figure's parts inside ONE
  always_redraw returning a VGroup, rather than several always_redraws that each
  recompute the same geometry. Keep sweeps to ~3s.
- Angles and perpendicularity are claims: mark them with Angle / RightAngle
  rather than relying on the drawing looking about right."""

_LINEAR_ALGEBRA = """VECTORS & LINEAR ALGEBRA
- Position vectors as arrows FROM the origin TO a point; addition as tip-to-tail
  placement (GrowArrow the second arrow starting where the first ends); scalar
  multiplication as stretching along the same line.
- A vector equation of a line as a fixed point plus a direction arrow, with a
  second point built by adding a scaled copy of that direction
  (TransformFromCopy + shift).
- The scalar product as one vector projected onto another (a short perpendicular
  Line dropped onto the second vector's direction).
- A matrix as a TRANSFORMATION acting visibly on something: Transform a grid,
  the unit square, or a set of arrows, so input-to-output correspondence is
  watchable. A determinant as the signed area of the transformed unit square.
  An eigenvector as a direction that only scales — its arrow stays on its own
  line while other arrows swing off theirs.
- Use 2D for 2x2 work. True 3D only for genuinely spatial vectors, planes or
  volumes."""

_CALCULUS = """CALCULUS
- Plot on Axes; roots as x-intercept Dots, intersections where two plots meet.
- A derivative as a tangent's changing slope. Two good options: (discrete)
  Create a wide secant with get_secant_slope_group(x, graph, dx=1.0, ...) then
  Transform it into a narrow one (dx=0.01) — the gradient settling onto the
  tangent, best for a single before/after; or (continuous) THE TANGENT SWEEP —
  one ValueTracker on x driving an always_redraw tangent Line that slides along
  the curve so the slope visibly changes at every point, best when "how the
  gradient varies along the curve" is the point (this is the verified
  CONTROLLED CONTINUOUS MOTION tangent pattern — obey its render-cost limits).
- A limit as a Dot approaching along the curve (MoveAlongPath), OR a single
  ValueTracker driving the point continuously toward the limiting value with a
  coupled readout — whichever makes the approach clearer.
- Stationary points: a SHORT HORIZONTAL tangent Line at each one — horizontality
  is the visual definition of gradient zero. Distinguish a maximum from a
  minimum by sliding a tangent through the point so its slope visibly changes
  sign; at an inflection the curve's bend reverses while the tangent's sign
  holds. Plotting f'(x) on aligned Axes beneath f(x) makes the stationary
  points of f line up with the roots of f'.
- Integration as get_area filling under a curve; a Riemann sum refining via
  get_riemann_rectangles with smaller dx (Transform coarse -> fine).
- Trapezium rule: build trapezia from Polygon(axes.c2p(x0,0),
  axes.c2p(x0,f(x0)), axes.c2p(x1,f(x1)), axes.c2p(x1,0)) via LaggedStart, then
  Transform a few wide ones into many narrow ones so the shrinking error against
  the true get_area is visible.
- Iteration / root-finding: the standard visual is a cobweb/staircase — plot
  y=g(x) and the line y=x on the same Axes, then a zig-zag of alternating
  vertical and horizontal Lines bouncing between them (LaggedStart) converging
  on (or escaping from) the root. For a sign-change argument, show the curve
  crossing the x-axis between two marked points.
- Volume of revolution is one of the few genuinely 3D-worthy maths topics: a
  Surface built from the function, or one representative disc whose radius is
  f(x). If the region plus a single rotating cross-section conveys it, PREFER
  the 2D version.
- Parametric motion via plot_parametric_curve + a Dot on MoveAlongPath."""

_PROBABILITY_STATISTICS = """PROBABILITY & STATISTICS
- Probability as a tree, a partitioned sample-space rectangle, or proportional
  bars — a structure the viewer can count, not a stated number.
- A distribution as a plotted curve with a shaded region (get_area). Show a
  BINOMIAL (discrete) as separated Rectangles with gaps and a NORMAL
  (continuous) as a smooth curve; never blur that distinction.
- Hypothesis testing: the critical region is a shaded TAIL (get_area over the
  tail x_range in a warning colour, the rest neutral), with the test statistic
  dropped in as a Dot or vertical Line so the viewer sees at once whether it
  lands inside. A two-tailed test shades BOTH ends with half the area each.
- Standard deviations as marked equal intervals either side of the mean, with
  nested shaded areas.
- A histogram or bar chart is a row of scaled Rectangles (height ~ frequency,
  built with LaggedStart) — do NOT use the BarChart class: it renders its
  labels with Tex and LaTeX is not installed here, so it will fail.
- A box plot as a Line (whiskers) with a Rectangle (the box) in correct
  proportion; correlation as a scatter of Dots with a Line fitted through."""

_DISCRETE_ALGORITHMS = """DISCRETE STRUCTURES & ALGORITHMS
- Sets, logic and graphs as nodes + edges; membership and relations as
  containment or connection, not as prose.
- An algorithm as state changing on ONE small concrete example — highlight the
  element under consideration at each step (a colour change or Indicate) and
  let the structure visibly update. A viewer should be able to follow the run,
  not read pseudocode.
- Recursion/divide-and-conquer as a structure splitting into parts and results
  recombining; a counter or accumulator as a quantity that grows."""

_MECHANICS = """MECHANICS (kinematics, forces, energy, momentum, circular motion, SHM)
- Kinematics: a Dot at successive positions with EVEN spacing for constant
  velocity and WIDENING spacing for acceleration — the spacing carries the
  physics. Velocity as an arrow whose length tracks speed. The signature
  visual is GRAPH CORRESPONDENCE: displacement-time above velocity-time, the
  gradient of the first matching the height of the second (a tangent Line and a
  get_vertical_line moving together), and AREA under v-t as displacement
  (get_area). Projectiles: a constant horizontal component and an accelerating
  vertical one, tracing the parabola with plot_parametric_curve + MoveAlongPath.
- Forces: free-body arrows FROM the body, lengths proportional to magnitude (a
  bigger force MUST look longer). Resolve into components with DashedLine parts
  and a RightAngle mark; equilibrium as arrows closing tip-to-tail into a
  polygon; an inclined plane with weight resolved along and normal to the
  slope. Newton's third-law pairs act on DIFFERENT bodies — drawing both on one
  body is a physics error.
- Moments: a beam on a pivot with each force's PERPENDICULAR distance drawn as
  a DashedLine to its line of action; balance is the two turning effects
  visibly matching, and a longer distance must LOOK longer. Connected particles
  over a pulley share ONE tension magnitude and ONE acceleration magnitude —
  that shared value is the whole modelling assumption. Friction opposes the
  direction of (attempted) motion, along the surface. Hooke's law as extension
  proportional to load, with a force-extension plot that is straight while
  elastic and then bends.
- Energy: a bar per store (kinetic, gravitational, elastic, thermal) where the
  TOTAL height stays constant while energy moves between bars, paired with the
  physical object so the viewer sees which configuration matches which split.
  Work done as get_area under a force-displacement graph.
- Momentum: before/after panels with velocity arrows proportional to speed and
  masses as differently-sized shapes; the summed momentum arrow must be
  IDENTICAL before and after — that identity is the point. Elastic vs inelastic
  shows in whether the kinetic-energy bars still match.
- Circular motion: MoveAlongPath around a Circle with the centripetal arrow
  ALWAYS to the centre and velocity ALWAYS tangential (draw the radius and mark
  the RightAngle). Never draw an outward "centrifugal" force in an inertial
  frame. Removing the force sends the object along the tangent.
- SHM: acceleration points BACK toward equilibrium and grows with displacement
  — a restoring-force arrow that flips side to side and is longest at maximum
  displacement. The strongest visual is COUPLED CONTINUOUS MOTION: one
  ValueTracker (phase or time) drives BOTH the oscillator's position AND the
  point on the displacement-time sine beside it, so the mass and the graph move
  in genuine lockstep and the curve is generated by the motion (the verified
  CONTROLLED CONTINUOUS MOTION mechanism-with-coupled-effect pattern; keep it
  ~3s and let geometry, not per-frame Text, carry any value). A discrete Dot
  tracing an already-drawn sine is an acceptable fallback when reliability
  matters more. KE and PE bars swap while their sum holds. Damping as a
  decreasing-amplitude envelope."""

_WAVES = """WAVES
- A plotted sine where amplitude, wavelength, frequency and phase are
  measurable, LABELLED distances — a double-headed arrow spanning one
  wavelength beats the word "wavelength".
- A travelling wave should actually TRAVEL: one ValueTracker on phase driving an
  always_redraw sine so the waveform propagates continuously, rather than jumping
  between static frames (the verified CONTROLLED CONTINUOUS MOTION wave-phase
  pattern — keep it ~3s, one reactive plot). Superposition as two waves
  Transforming into their sum, or (stronger) two phase-driven waves plus their
  live sum so the reinforcement/cancellation is watched as the phases slide; a
  standing wave as fixed nodes with antinodes growing between them.
- Reflection, refraction, diffraction and interference as staged geometric
  constructions with correct angles and path differences.
- Distinguish transverse from longitudinal explicitly: longitudinal is a row of
  Dots bunching into compressions and spreading into rarefactions, NOT a
  transverse sine wave."""

_ELECTRICITY = """ELECTRICITY & CIRCUITS
- Current as charge carriers (Dots) drifting along a conductor at a rate that
  visibly matches the current; potential difference as an energy drop across a
  component; resistance as an impediment that slows the carriers.
- I-V characteristics on Axes: straight for an ohmic conductor, curved for a
  filament lamp or diode — the SHAPE is the physics.
- Circuits as clean node-and-edge diagrams from straight Lines with
  right-angled corners and labelled components; show the path with animated
  Dots or ShowPassingFlash along the wires. Series: the SAME current
  everywhere, p.d.s adding. Parallel: the SAME p.d. across branches, current
  splitting — animate the split at the junction. Show a change (a switch
  closing, a resistor added) by re-animating the flow, not by relabelling.
- Capacitors: charge accumulating on two plates while the charging current
  DECREASES, with the exponential charge/discharge curve on Axes and the time
  constant marked as a specific interval; stored energy as get_area under a
  charge-voltage plot.
- Electric fields: radial lines OUT of positive and INTO negative charge, with
  arrowheads and correct symmetry; a uniform field between parallel plates as
  evenly spaced parallel arrows. Field lines never cross and never start or end
  in empty space. A test charge's force is tangent to a field line;
  equipotentials run perpendicular to the field lines."""

_MAGNETISM = """MAGNETISM & ELECTROMAGNETIC INDUCTION
- Use the standard page convention: OUT of the page is a Circle with a Dot at
  its centre; INTO the page is a Circle with Cross(Circle(...)) through it.
- The field around a straight current-carrying wire is concentric Circles with
  the correct sense; a bar magnet's field loops from N to S.
- The motor effect involves three mutually perpendicular directions (current,
  field, force) — draw them with explicit RightAngle marks and get the
  handedness right; a reversed force is a physics error.
- Induction is driven by CHANGING flux, so the animation must show something
  changing — a magnet entering a coil, an area shrinking, a field
  strengthening. The induced current appears only WHILE the change happens and
  stops when it stops. Lenz's law means the induced effect visibly OPPOSES the
  change that caused it; do not imply the effect precedes or causes its own
  driver."""

_OPTICS = """OPTICS
- Ray diagrams with straight rays and correct angles measured from the NORMAL —
  draw the normal as a DashedLine and mark the angles with Angle.
- Refraction bends toward the normal entering a denser medium; total internal
  reflection occurs only past the critical angle and only going into a less
  dense medium.
- Lens and mirror images built from the standard principal rays, with the image
  located where the rays actually meet (or appear to)."""

_THERMAL = """THERMAL PHYSICS
- Particles as Dots whose speed and spacing represent temperature and state;
  heating as faster motion.
- A change of state is a change in ordering/spacing at CONSTANT temperature —
  pair it with a temperature-time graph showing the flat plateau, because the
  plateau is the insight.
- Gas laws as a pressure-volume plot on Axes with a piston Rectangle changing
  size alongside, so the graph and the apparatus move together.
- Energy transfer as a directional flow between labelled regions."""

_QUANTUM_NUCLEAR = """QUANTUM, PARTICLE & NUCLEAR PHYSICS
- A photon is a DISCRETE packet (a small marked object or short wavy Line),
  never a continuous stream — the quantisation is the point. Atomic energy
  levels as UNEQUALLY spaced horizontal Lines with an electron Dot jumping
  between them, emitting or absorbing a photon whose colour matches the gap;
  the line spectrum is thin coloured Rectangles at positions set by those gaps.
- Photoelectric effect: electrons are released only ABOVE a threshold
  frequency — show a below-threshold photon producing nothing however many
  arrive, since that failure is the evidence.
- Standard model structure as a grouped grid of labelled Dots/Circles with
  colour marking the family; a hadron as its quarks inside a containing shape
  (three for a baryon, a quark-antiquark pair for a meson).
- Interactions as a Feynman-style diagram: straight Lines meeting at a vertex
  Dot, a distinctly styled (wavy/dashed) exchange boson between vertices, and
  time running consistently in ONE direction. Tally charge, baryon and lepton
  number on each side to show conservation.
- Nuclei as clustered Dots in two colours. Alpha decay as a two-proton
  two-neutron cluster leaving; beta-minus as a neutron becoming a proton with
  an electron emitted; gamma as an energy-level drop.
- Radioactive decay as an exponential curve with successive half-lives marked
  as EQUAL x intervals each halving y (get_vertical_line at each) — the equal
  spacing IS the concept. Binding energy per nucleon as the curve peaking near
  iron, with fission on the heavy side and fusion on the light side both moving
  TOWARD the peak."""

_ASTROPHYSICS = """ASTROPHYSICS & GRAVITATION
- Orbits as an ellipse or circle traced by MoveAlongPath with the central body
  at a FOCUS (not the centre) — faster near periapsis when Kepler's second law
  is the point, with equal-area sweeps as shaded Sectors/Polygons.
- Gravitational fields are radial and INWARD, always attractive: there is no
  repulsive case and drawing one is a physics error. The parallel with the
  electric field (both radial, both inverse-square) is worth drawing, but state
  the contrast — gravity has one sign, charge has two.
- Hertzsprung-Russell diagrams as a scatter of Dots on Axes with the main
  sequence a visible diagonal band; the temperature axis is conventionally
  REVERSED.
- Redshift as thin Rectangle spectral lines keeping their relative spacing
  while shifting bodily toward the red end — the preserved pattern is what
  identifies the shift.
- Inverse-square dimming as the same light spread over a growing area; parallax
  as a nearby star apparently shifting against fixed background Dots as the
  observation point moves.
- A gravitational "potential well" is a metaphor: do not let it imply the well
  is a physical surface."""

_GENERAL = """GENERAL SCENE (no single specialist domain applies — this is NOT permission
for a thinner or less-considered scene; it means invent the metaphor rather than
borrow one, and it deserves the SAME visual effort as any domain scene):
- This scene is an introduction, a recap, a framing question, a transition, or
  otherwise not tied to one technical domain. Build the visual from the
  lesson's PURPOSE — comparison, process, cause and effect, structure,
  hierarchy, quantity, transformation — using the core visual-storytelling
  rules already given, not a placeholder title card.
- Do not invent domain notation, axes, field lines or equations the scene does
  not actually need, and do not reach for a specialist diagram to look rigorous.
- REACH FOR DEPTH WHEN IT HELPS: general scenes (comparisons, overviews,
  before/after framing) are exactly where 2.5D layering — set_z_index, scale,
  opacity — often clarifies structure. Consider whether stacking, nesting, or
  a foreground/background split would make this scene's idea clearer before
  defaulting to a flat single-layer composition. See LIFT INTO DEPTH above.
- BUILD ONE STRONG BESPOKE VISUAL, not a generic box-and-arrow diagram: a
  process as parts assembling or flowing; a comparison as two arrangements
  transforming into each other or standing side by side with a shared visual
  language; cause-and-effect as one change visibly producing another; a
  hierarchy as a structure that grows, nests, or ranks by size/position; a
  quantity as something filling, splitting, or scaling proportionally.
- USE THE FULL TOOLKIT even without a domain to anchor it: TransformFromCopy
  for a derivation-like progression, LaggedStart for parts of a whole arriving
  in order, a short ArcBetweenPoints move for something transferring or
  flowing, dim-the-rest to focus attention on one element among several. A
  general scene is where inventing a fresh, concrete metaphor matters MOST —
  there is no formula to fall back on, so make the metaphor specific and
  visual rather than abstract and textual."""


_MODULES = {
    "general": _GENERAL,
    "algebra": _ALGEBRA,
    "geometry": _GEOMETRY,
    "linear_algebra": _LINEAR_ALGEBRA,
    "calculus": _CALCULUS,
    "probability_statistics": _PROBABILITY_STATISTICS,
    "discrete_algorithms": _DISCRETE_ALGORITHMS,
    "mechanics": _MECHANICS,
    "waves": _WAVES,
    "electricity": _ELECTRICITY,
    "magnetism": _MAGNETISM,
    "optics": _OPTICS,
    "thermal": _THERMAL,
    "quantum_nuclear": _QUANTUM_NUCLEAR,
    "astrophysics": _ASTROPHYSICS,
}

# Fail loudly at import if the taxonomy and the modules ever drift apart.
_missing = sorted(set(DOMAIN_TAGS) - set(_MODULES))
if _missing:  # pragma: no cover - guards a developer mistake, not runtime input
    raise RuntimeError(f"domain tags without a guidance module: {_missing}")


def known_tags() -> Sequence[str]:
    """The controlled taxonomy, in canonical order."""
    return DOMAIN_TAGS


def normalize_tags(tags: Optional[Iterable[str]]) -> List[str]:
    """Filter to known tags, de-duplicate (first wins), and bound the count.

    Defensive: routing must never crash scene generation. Unknown tags are
    rejected at the schema boundary; anything odd that reaches here is dropped
    and the safe "general" default applies.
    """
    out: List[str] = []
    for tag in tags or ():
        if not isinstance(tag, str):
            continue
        key = tag.strip().lower().replace("-", "_").replace(" ", "_")
        if key in _MODULES and key not in out:
            out.append(key)
    if not out:
        return ["general"]
    # A specialist tag makes a co-selected "general" meaningless.
    if len(out) > 1:
        out = [t for t in out if t != "general"] or ["general"]
    return out[:MAX_TOTAL_DOMAIN_TAGS]


def modules_for(tags: Optional[Iterable[str]]) -> List[str]:
    """Return the selected tags (normalized) — the audit view of routing."""
    return normalize_tags(tags)


def build_domain_section(tags: Optional[Iterable[str]]) -> str:
    """Assemble the domain guidance block for the selected tags only.

    A bare "general" scene gets the short general module without the accuracy
    preamble (it makes no domain claims); any specialist scene gets the
    accuracy rule plus its 1-3 modules, primary first.
    """
    selected = normalize_tags(tags)
    if selected == ["general"]:
        return f"{_DOMAIN_HEADER}\n\n{_GENERAL}"
    body = "\n\n".join(_MODULES[t] for t in selected)
    return f"{_DOMAIN_HEADER}\n\n{_ACCURACY_RULE}\n\n{body}"


def tag_menu_for_prompt() -> str:
    """The taxonomy rendered for the storyboard prompt (one line per tag)."""
    descriptions = {
        "general": "intros, recaps, framing questions, non-specialist scenes",
        "algebra": "expressions, functions, graph transformations, exponentials/logs, sequences & series",
        "geometry": "coordinate geometry, circles, triangles, trigonometry, angles",
        "linear_algebra": "vectors, vector geometry, matrices, transformations, determinants, eigenvectors",
        "calculus": "limits, differentiation, integration, area/accumulation, numerical methods",
        "probability_statistics": "probability, distributions, sampling, hypothesis testing, data displays",
        "discrete_algorithms": "sets, logic, graphs/networks, algorithms, recursion",
        "mechanics": "kinematics, forces, moments, energy, momentum, circular motion, SHM",
        "waves": "wave properties, superposition, standing waves, interference, sound",
        "electricity": "current, voltage, resistance, circuits, capacitors, electric fields",
        "magnetism": "magnetic fields, motor effect, electromagnetic induction",
        "optics": "reflection, refraction, lenses, mirrors, ray diagrams",
        "thermal": "temperature, heat transfer, changes of state, gas laws",
        "quantum_nuclear": "photons, energy levels, particle physics, radioactivity, nuclear energy",
        "astrophysics": "orbits, gravitation, stars, cosmology, redshift",
    }
    return "\n".join(f"  - {t}: {descriptions[t]}" for t in DOMAIN_TAGS)
