"""Per-domain visual-reasoning guidance, selected by storyboard domain tags.

Previously every scene received one ~5,200-token block covering every maths and
physics topic at once. Flash-Lite has ample context for that, so this is not a
capacity fix — it is an *instruction-dilution* fix: a calculus scene that also
reads magnetism, optics and astrophysics rules follows its own rules less
consistently and drifts toward generic diagrams.

Each module below is the concise, animation-relevant slice for one tag in
:data:`schemas.DOMAIN_TAGS`. Modules state visual opportunities and correctness
constraints; they never prescribe a fixed diagram or a scene template.

Every Manim construct referenced here was render-verified in this environment
(Manim CE 0.19.1, cairo, no LaTeX) before being written down — notably the
cobweb/staircase iteration diagram, ``Cross(Circle(...))`` for into-page field
symbols, ``Angle`` / ``RightAngle`` marks, and ``Polygon`` trapezia. The
``BarChart`` class is excluded on purpose: its ``__init__`` builds ``Tex``
labels and therefore requires a LaTeX binary that is not installed.
"""

from __future__ import annotations

from typing import Iterable, List, Optional, Sequence

from schemas import A_LEVEL_MATH_TOPICS, DOMAIN_TAGS, MAX_TOTAL_DOMAIN_TAGS

# --------------------------------------------------------------------------- #
# Correctness preamble — always sent with ANY specialist module (but not with a
# bare "general" scene, which has no domain claims to get wrong).
# --------------------------------------------------------------------------- #
_DOMAIN_HEADER = """DOMAIN VISUAL REASONING (guidance for THIS scene's subject — not a template.
Infer the right metaphor from the scene's objective; never force a listed
technique into a scene that does not need it):"""

_ACCURACY_RULE = """ACCURACY: every arrow, field line, particle, axis, rotation and trajectory must
represent a REAL relationship, never decoration. A metaphor must not imply a
false claim. If you cannot say what a mark means, do not draw it."""


# --------------------------------------------------------------------------- #
# MATHEMATICS modules
# --------------------------------------------------------------------------- #

_ALGEBRA = """ALGEBRA, FUNCTIONS & SEQUENCES
- Derivations: keep aligned expressions with a STABLE colour per term and
  TransformFromCopy one line into the next, so a term visibly becomes its
  successor. Never cut to a disconnected new text slide.
- Graph transformations: Transform one axes.plot(f) directly into axes.plot(g)
  so the curve visibly SLIDES, STRETCHES or FLIPS — the clearest way to show
  f(x)+a, f(x-a), a*f(x), -f(x), f(-x).
- Exponentials & logarithms: plot growth/decay and mark equal-width steps along
  x with get_vertical_line so the constant doubling/halving ratio is VISIBLE
  rather than asserted; a half-life or doubling time is one such interval. A
  logarithm is the inverse — reflect the exponential in the line y=x. For
  log-linearisation, Transform the curved plot into a straight Line on
  relabelled axes; the straightening IS the insight.
- Asymptotes: draw them as thin DashedLine objects BEFORE the curve, then
  Create the curve approaching without touching. Mark excluded points with a
  hollow Dot (a small Circle, no fill); show domain/range as highlighted
  intervals along the axes.
- Sequences & series: terms as a row of dots/bars arriving one at a time
  (LaggedStart) — spreading for a divergent sequence, settling toward a fixed
  value for a convergent one. A partial sum as a growing bar or a staircase of
  stacked rectangles. A recurrence must build each term FROM the previous one
  (TransformFromCopy), never independently."""

_GEOMETRY = """GEOMETRY, COORDINATE GEOMETRY & TRIGONOMETRY
- Coordinate geometry: a line as axes.plot(linear fn) or a Line between two
  axes.c2p(...) points, with a "rise over run" right-triangle built from two
  short Lines to show gradient; a circle via Circle(radius=..) centred with
  axes.c2p; a tangent as a Line touching at exactly one point (check visually
  that it does not cross).
- Trigonometry — THE SWEEP (the defining trig animation; reach for it whenever
  the link between angle and ratio is the point). ONE ValueTracker holds the
  angle and drives everything at once: the radius Line on a unit circle, a
  dashed PROJECTION line from the point on the circle to the horizontal axis,
  and the matching point on the sin/cos curve on Axes beside it. The curve is
  GENERATED by the sweep, not traced over a curve that already exists — either
  redraw a partial plot, axes.plot(f, x_range=[0, t.get_value()]), or put
  Create(curve) in the SAME self.play(...) as the tracker so both run on one
  clock. NOTE: the general "use Rotate sparingly" caution does NOT apply here —
  in trigonometry the angle IS the variable, so a full continuous sweep is the
  content, not decoration.
  Say what the projection MEANS, because students are rarely shown it: the
  vertical drop from the circle point to the axis IS sin θ, and the horizontal
  offset IS cos θ. The sine is a projection, not a number from a table.
- Tangent Function (tan θ) Visual:
  Draw a vertical DashedLine at x = 1 (tangent to the unit circle). Extend the
  rotating radius line outward until it intersects x = 1. The vertical height
  of this intersection point above the x-axis IS tan θ = sin θ / cos θ. As θ
  approaches 90° (PI/2), the intersection moves toward infinity, showing WHY
  tan θ has a vertical asymptote!
- Small Angle Approximations (sin θ ≈ θ, tan θ ≈ θ, cos θ ≈ 1 - θ²/2 for small θ):
  Zoom in near the origin on Axes. Plot y = sin(x) in cyan and the line y = x
  in bright yellow. For small angles (θ < 0.2 rad ≈ 11°), show the curve and
  the straight line overlapping almost identically.
- Why trig works at all — SCALE INVARIANCE: one tracker on a scale factor grows
  and shrinks a right triangle while the ratio opp/hyp stays FIXED. The triangle
  visibly changes size; the ratio does not. This answers "why does a ratio
  depend only on the angle?", which a static diagram cannot.
- Solving trig equations IN AN INTERVAL (the most-missed A-level skill — students
  find one solution and stop): draw y = k as a horizontal DashedLine across the
  curve over the whole stated range, then Dot EVERY intersection (LaggedStart)
  and drop a line from each to the x-axis. Map the solutions back to the unit
  circle / CAST quadrants so the viewer sees WHY there is more than one. Never
  show only the principal value.
- The Pythagorean identity is not a fact to memorise, it is Pythagoras: on the
  unit circle, the cos leg, the sin leg and the radius form a right triangle
  with hypotenuse 1, so sin²θ + cos²θ = 1 falls straight out. Mark the right
  angle (RightAngle) and colour each leg to match its label.
- Sine rule: a genuine non-right triangle as a Polygon, sides and angles marked
  (Angle arcs), with each related side-angle PAIR sharing a colour — the
  pairing is the entire content of the sine rule.
- Cosine rule is about the INCLUDED angle between the two known sides, not
  about pairs — highlight that angle specifically. The strongest way to show it
  is as a GENERALISED PYTHAGORAS: hold two sides fixed, sweep the included
  angle toward 90° with a ValueTracker, and let the −2ab·cos C term visibly
  shrink to nothing, leaving c² = a² + b². The two "rules" are then one rule,
  which is far more memorable than two formulas to look up.
- CHOOSING WHICH RULE is the actual exam skill, so make the choice VISIBLE
  rather than announcing it: light up what is known on the triangle and dim the
  rest. If a complete side-and-its-opposite-angle PAIR is lit, the sine rule is
  available; if instead two sides and the angle BETWEEN them are lit (or all
  three sides), it is the cosine rule. The lit quantities should select the
  rule on screen before its name appears.
- Bearings (for real-world distance/navigation problems): draw the NORTH arrow
  first, measure the bearing CLOCKWISE from north, and write it as three
  figures (065°, not 65°). A bearing drawn anticlockwise, or from another
  reference direction, is a convention error — treat it as seriously as a
  reversed force arrow.
- Modelling a real situation: when a scene starts from a real context (two
  towns, a ship, a surveyor), show the ABSTRACTION happening — the real objects
  fade back and dim while the triangle is drawn over them and comes forward
  (set_z_index + opacity, the flat -> layered lift). Keeping the context dimly
  behind the triangle is what stops it becoming "just a maths diagram".
- CAST / quadrant sign work: shade the relevant unit-circle quadrant (Sector)
  and show the sign of each ratio there.
- RENDER COST & ZERO-REGRESSION RULE (measured here, 480p15 — a sweep scene is easy
  to make 10x slower than it needs to be): reactive GEOMETRY is cheap (~5s for
  several always_redraw shapes over a 3s sweep), but a Text rebuilt every frame
  via always_redraw costs ~3x MORE THAN THE ENTIRE REST OF THE SCENE. Prefer to let
  the geometry carry the value — the projection line's length IS sin θ — with a
  couple of STATIC labels. If a changing number is genuinely the point, update it
  a few times rather than every frame. Build all of one figure's parts inside ONE
  always_redraw returning a VGroup, rather than several always_redraws that each
  recompute the same geometry. Keep sweeps to ~3s.
- Angles and perpendicularity are claims: mark them with Angle / RightAngle
  rather than relying on the drawing looking about right."""

_LINEAR_ALGEBRA = """VECTORS & LINEAR ALGEBRA
- Position vectors as arrows FROM the origin TO a point; addition as tip-to-tail
  placement (GrowArrow the second arrow starting where the first ends); scalar
  multiplication as stretching along the same line.
- Matrix Transformations — THE COLUMN BASIS RULE (3Blue1Brown signature visual):
  A matrix [[a, b], [c, d]] is NOT a box of 4 numbers — it is a instruction for
  where space goes:
  - Column 1 [a, c]^T is WHERE i_hat (1,0) LANDS. Draw i_hat as a thick GREEN arrow.
  - Column 2 [b, d]^T is WHERE j_hat (0,1) LANDS. Draw j_hat as a thick RED arrow.
  - Use NumberPlane for the background grid. Transform i_hat -> [a,c], j_hat -> [b,d],
    and the NumberPlane simultaneously using play(i_hat.animate.move_to(...),
    j_hat.animate.move_to(...), plane.animate.apply_matrix([[a,b],[c,d]])).
- Clean Matrix Notation (No-LaTeX Bracket Pattern):
  Never write messy text strings like "[[2,1],[1,3]]". Render matrices by placing
  4 distinct Text/MathTex entries inside a 2x2 grid, flanked by left and right
  bracket lines (or bracket Arc/Line pairs forming [ ]). Ensure generous spacing
  (buff=0.35) so numbers never touch or overlap bracket borders.
- Determinant as Area & Orientation:
  - The determinant det(A) = ad - bc is the SIGNED AREA of the unit square after transformation.
  - Draw the unit square (Polygon between (0,0), i_hat, i_hat+j_hat, j_hat) before
    transformation, then Transform it into the transformed parallelogram.
  - Shade the transformed parallelogram with get_area or a semi-transparent Polygon.
  - If det(A) < 0, highlight that space was FLIPPED (orientation inversion / chirality change).
  - If det(A) = 0, show the 2D plane collapsing into a 1D line (rank 1) or 0D point (rank 0).
- Eigenvectors & Eigenvalues:
  - An eigenvector is a line where vectors DO NOT ROTATE during transformation — they only stretch by factor lambda.
  - Draw the eigenvector as a long dashed line. Place a vector arrow on it and show it stretching by lambda while off-axis vectors rotate off their lines.
- Matrix Multiplication (Composition):
  - AB means apply A FIRST, then apply B to the result. Show two sequential grid warps."""

_CALCULUS = """CALCULUS
- Plot on Axes; roots as x-intercept Dots, intersections where two plots meet.
- A derivative as a tangent's changing slope. Two good options: (discrete)
  Create a wide secant with get_secant_slope_group(x, graph, dx=1.0, ...) then
  Transform it into a narrow one (dx=0.01) — the gradient settling onto the
  tangent, best for a single before/after; or (continuous) THE TANGENT SWEEP —
  one ValueTracker on x driving an always_redraw tangent Line that slides along
  the curve so the slope visibly changes at every point, best when "how the
  gradient varies along the curve" is the point (this is the verified
  CONTROLLED CONTINUOUS MOTION tangent pattern — obey its render-cost limits).
- Product Rule (uv)' = u'v + uv' (Visual Area Expansion):
  Visualize u * v as a Rectangle of width u and height v. As u and v change,
  show the area expanding by adding a vertical strip (u * dv) and a horizontal
  strip (v * du), with the tiny corner (du * dv) shrinking to 0 as dx -> 0.
- Chain Rule dy/dx = (dy/du) * (du/dx):
  Visualize as two linked rate sliders or gear wheels: input x drives intermediate u
  at rate du/dx, which drives output y at rate dy/du. The overall rate is the product.
- Fundamental Theorem of Calculus (Area Accumulator):
  - Let A(x) = integral from a to x of f(t) dt (shaded get_area from a to x).
  - Move x right by a small step dx using ValueTracker. Show a thin vertical strip of
    width dx and height f(x) being added to the area: dA = f(x) * dx.
  - Therefore dA/dx = f(x) — the rate of area accumulation IS the height of the curve!
- Second Derivative f''(x), Concavity & Inflection Points:
  - Concave Up (f'' > 0): Tangent line sits BELOW the curve; gradient f' is INCREASING.
  - Concave Down (f'' < 0): Tangent line sits ABOVE the curve; gradient f' is DECREASING.
  - Point of Inflection: The point where f''(x) = 0 and concavity reverses (tangent crosses through the curve).
- Differential Equations & Slope Fields:
  - Draw a Slope Field (a grid of short Line segments whose slopes match dy/dx = f(x,y)).
  - Animate a Dot tracing a solution curve through the slope field, aligning with the tangent lines at every point.
- Stationary points: a SHORT HORIZONTAL tangent Line at each one — horizontality
  is the visual definition of gradient zero. Distinguish a maximum from a
  minimum by sliding a tangent through the point so its slope visibly changes
  sign; at an inflection the curve's bend reverses while the tangent's sign
  holds. Plotting f'(x) on aligned Axes beneath f(x) makes the stationary
  points of f line up with the roots of f'.
- Integration as get_area filling under a curve; a Riemann sum refining via
  get_riemann_rectangles with smaller dx (Transform coarse -> fine).
- Trapezium rule: build trapezia from Polygon(axes.c2p(x0,0),
  axes.c2p(x0,f(x0)), axes.c2p(x1,f(x1)), axes.c2p(x1,0)) via LaggedStart, then
  Transform a few wide ones into many narrow ones so the shrinking error against
  the true get_area is visible.
- Iteration / root-finding: the standard visual is a cobweb/staircase — plot
  y=g(x) and the line y=x on the same Axes, then a zig-zag of alternating
  vertical and horizontal Lines bouncing between them (LaggedStart) converging
  on (or escaping from) the root. For a sign-change argument, show the curve
  crossing the x-axis between two marked points.
- Volume of revolution is one of the few genuinely 3D-worthy maths topics: a
  Surface built from the function, or one representative disc whose radius is
  f(x). If the region plus a single rotating cross-section conveys it, PREFER
  the 2D version.
- Parametric motion via plot_parametric_curve + a Dot on MoveAlongPath."""

_PROBABILITY_STATISTICS = """PROBABILITY & STATISTICS
- Probability as a tree, a partitioned sample-space rectangle, or proportional
  bars — a structure the viewer can count, not a stated number.
- A distribution as a plotted curve with a shaded region (get_area). Show a
  BINOMIAL (discrete) as separated Rectangles with gaps and a NORMAL
  (continuous) as a smooth curve; never blur that distinction.
- Hypothesis testing: the critical region is a shaded TAIL (get_area over the
  tail x_range in a warning colour, the rest neutral), with the test statistic
  dropped in as a Dot or vertical Line so the viewer sees at once whether it
  lands inside. A two-tailed test shades BOTH ends with half the area each.
- Standard deviations as marked equal intervals either side of the mean, with
  nested shaded areas.
- A histogram or bar chart is a row of scaled Rectangles (height ~ frequency,
  built with LaggedStart) — do NOT use the BarChart class: it renders its
  labels with Tex and LaTeX is not installed here, so it will fail.
- A box plot as a Line (whiskers) with a Rectangle (the box) in correct
  proportion; correlation as a scatter of Dots with a Line fitted through."""

_DISCRETE_ALGORITHMS = """DISCRETE STRUCTURES & ALGORITHMS (DSA, ARRAYS & TERMINAL VISUALS)
- STRICT DOMAIN SCOPING RULE (CRITICAL):
  - The Split-Screen Code Terminal & Data Structure Arena layout is ONLY to be used
    for DSA / LeetCode / Coding Algorithm topics (e.g. `dsa`, `arrays`, `two_pointers`,
    `binary_search`, `hashing`, `sliding_window`, `kadane`, `intervals`, `greedy`).
  - DO NOT render a Code Terminal in Geometry, Trigonometry, Calculus, Physics, or
    General concept scenes (e.g. "Why honeycombs are hexagonal"). General/physics
    scenes must use standard mathematical diagrams, geometry, or graphs instead!

- Glassmorphic IDE & Code Terminal Styling (Premium LeetCode Aesthetic):
  - Left Panel (x = -3.5): Data Structure Memory Arena.
    - Array Memory Cells: RoundedRectangle(corner_radius=0.12, width=1.1, height=1.1,
      stroke_color="#38bdf8", stroke_width=2.0, fill_color="#0f172a", fill_opacity=0.85).
    - Sub-Index Pills: Crisp index numbers (0, 1, 2...) below each cell in muted gray (#64748b).
    - Pointer Badges: Colored pointer arrows (Text "L", color="#22c55e" Green; Text "R",
      color="#ef4444" Red; Text "i", color="#38bdf8" Cyan; Text "mid", color="#eab308" Yellow).
  - Right Panel (x = +3.5): Syntax-Highlighted Glassmorphic Code Terminal.
    - Outer IDE Container: RoundedRectangle(corner_radius=0.25, width=6.2, height=4.6,
      stroke_color="#1e293b", stroke_width=2.5, fill_color="#0b0f19", fill_opacity=0.92).
    - Window Control Dots: 3 top-left dots (Red "#ef4444", Yellow "#eab308", Green "#22c55e").
    - Header Bar Title: Text("two_sum.py", font_size=14, color="#94a3b8") centered in window bar.
    - Syntax Color Palette: Monospaced Python/Pseudocode with purple keywords (#c084fc for def, for, in, if, return),
      cyan variables (#38bdf8), and orange values (#fb923c).
  - Active Line Tracker: Move a glowing line highlighter (SurroundingRectangle(line_text,
    color="#f59e0b", fill_color="#f59e0b", fill_opacity=0.15, stroke_width=2.0)) down line-by-line
    with a small leading arrow Text("▶", color="#f59e0b", font_size=12).
- Pattern 1: Linear Traversal & Accumulation (Sum/Product, Min/Max, Count, Streaks):
  - Animate scanning: pointer i steps right across cells (LaggedStart or ValueTracker).
  - Highlight current element (cell[i].set_fill(TEAL_C, opacity=0.4)).
  - Accumulator readout on left (e.g. "Sum: 14", "Max: 9") updates in step with i.
- Pattern 2: Linear Search & Occurrence Tracking (Target, First/Last/All, Existence):
  - Display Target callout card (e.g. "Target = 7").
  - Pointer i scans left to right: non-matching cells flash subtle red/grey; matching
    cell flashes bright GREEN (cell[i].set_fill(GREEN, opacity=0.6)) and locks.
- Pattern 3: Basic Array Manipulation (Swap, Reverse, Copy, Merge, Rotate, Compact):
  - Swapping: Draw two curved arcs (CurvedArrow or Arc) above the two swapping cells,
    then execute ReplacementTransform to cross their positions in 2.5D space.
  - Read/Write Pointers: Advance read_ptr and write_ptr independently for in-place compaction.
- Pattern 4: Basic Hashing & Frequency Mapping (Set Membership, Duplicates, Maps):
  - Render an adjacent Hash Set / Map grid on the left (e.g. "seen = {}").
  - When visiting arr[i], an Arrow or floating copy of the value flies into the Hash
    Set grid. If already present, the set cell pulses Coral RED (duplicate detected!).
- Pattern 5: Basic Two Pointers (Opposite Ends, Fast/Slow, Read/Write, Pair Search):
  - Opposite-End: Left pointer L (Green arrow) at index 0, Right pointer R (Red arrow)
    at N-1. Move L right (L += 1) or R left (R -= 1) based on comparison.
  - Fast/Slow: Slow pointer (slow) advances only on valid condition; Fast pointer (fast)
    scans every step.
- Pattern 6: Basic Sorting Patterns (Sort & Scan, Adjacent Compare, Grouping):
  - Unsorted array cells morph into sorted order via LaggedStart position shifts.
  - Show adjacent comparison brackets (VGroup of 2 cell outlines) sliding across array.
- Pattern 7: Basic Prefix & Suffix Patterns (Cumulative Sums, Ranges, Left-Right):
  - Render a secondary Prefix Array beneath the main array.
  - Show cumulative area/bar filling beneath each cell: prefix[i] = prefix[i-1] + arr[i].
- Pattern 8: Basic Matrix Traversal (Row/Col Major, Diagonals, Boundary, Transpose):
  - Render a 2D Grid of Squares (R x C).
  - Active cell (row, col) scans sequentially across rows or columns with a glowing
    cursor box. For matrix transpose, show symmetric cells swapping across the main diagonal.
- Pattern 9: Sliding Window (Fixed/Variable Size, Expand R / Shrink L, Window Sum/Freq):
  - Draw a glowing bounding box (RoundedRectangle, stroke_color=YELLOW) spanning arr[L:R+1].
  - Expanding: R arrow moves right $\to$ window box stretches `window.animate.surround(arr[L:R+1])`.
  - Shrinking: L arrow moves right when invalid $\to$ window box shrinks from left.
- Pattern 10: Prefix Sum Range Queries (Range Sum, Min/Max, Subarray Sums):
  - Display Prefix Array `P`. For range query `sum(L..R)`, highlight `P[R]` in Green
    and `P[L-1]` in Orange, showing `Subarray Sum = P[R] - P[L-1]`.
- Pattern 11: Binary Search & Range Bisection (Exact, Bounds, Insertion Point):
  - Display L (Green arrow at left bound), R (Red arrow at right bound), and Mid
    `mid = (L+R)//2` (Yellow arrow at midpoint).
  - Compare `arr[mid]` to target: gray out eliminated half (fade opacity to 0.2) and
    move L or R arrow to bisect the search space.
- Pattern 12: Intermediate Two Pointers (3Sum Anchor, Container Most Water, Partitioning):
  - 3Sum: Fix anchor pointer `i` (Cyan arrow), then run Two Pointers `L` and `R` on `arr[i+1:]`.
  - Container Most Water: Vertical bar lines at `L` and `R` with shaded blue area `(R-L)*min(hL, hR)`
    shrinking/growing as `L` or `R` moves inward.
- Pattern 13: Kadane's Algorithm & Subarray DP (Max/Min Subarray, Best Stock Profit):
  - Render dual meters on left: `Current Subarray Sum` and `Global Max Sum`.
  - At cell `i`: show choice `max(arr[i], current_sum + arr[i])` — if `arr[i]` restarts
    segment, current window flashes red and resets to start at `i`.
- Pattern 14: Interval Basics (Merge Intervals, Insert, Overlap Detection):
  - Render intervals as horizontal line segments `[start, end]` stacked vertically.
  - Sort by start time. Show active pointer checking `end1 >= start2`: if overlapping,
    the two segments morph (`Transform`) into one unified merged segment `[start1, max(end1, end2)]`.
- Pattern 15: Advanced Matrix Operations (Spiral Traversal, 90° Rotation, Transpose):
  - Spiral: 4 boundary arrows (`top`, `bottom`, `left`, `right`) shrinking inward after
    each row/column traversal sweep.
  - Rotation: Transpose cells across main diagonal, then reverse each row horizontally.
- Pattern 16: Greedy Arrays (Jump Game Reachability, Jump Counting, Local Optimal Choice):
  - Render `farthest_reach` indicator line above array (`max(farthest, i + nums[i])`).
  - As pointer `i` steps forward, update `farthest_reach` boundary line. If `i > farthest`,
    flash warning indicating unreachable destination."""

_MECHANICS = """MECHANICS (kinematics, forces, energy, momentum, circular motion, SHM)
- Kinematics: a Dot at successive positions with EVEN spacing for constant
  velocity and WIDENING spacing for acceleration — the spacing carries the
  physics. Velocity as an arrow whose length tracks speed. The signature
  visual is GRAPH CORRESPONDENCE: displacement-time above velocity-time, the
  gradient of the first matching the height of the second (a tangent Line and a
  get_vertical_line moving together), and AREA under v-t as displacement
  (get_area). Projectiles: a constant horizontal component and an accelerating
  vertical one, tracing the parabola with plot_parametric_curve + MoveAlongPath.
- Forces: free-body arrows FROM the body, lengths proportional to magnitude (a
  bigger force MUST look longer). Resolve into components with DashedLine parts
  and a RightAngle mark; equilibrium as arrows closing tip-to-tail into a
  polygon; an inclined plane with weight resolved along and normal to the
  slope. Newton's third-law pairs act on DIFFERENT bodies — drawing both on one
  body is a physics error.
- Moments: a beam on a pivot with each force's PERPENDICULAR distance drawn as
  a DashedLine to its line of action; balance is the two turning effects
  visibly matching, and a longer distance must LOOK longer. Connected particles
  over a pulley share ONE tension magnitude and ONE acceleration magnitude —
  that shared value is the whole modelling assumption. Friction opposes the
  direction of (attempted) motion, along the surface. Hooke's law as extension
  proportional to load, with a force-extension plot that is straight while
  elastic and then bends.
- Energy: a bar per store (kinetic, gravitational, elastic, thermal) where the
  TOTAL height stays constant while energy moves between bars, paired with the
  physical object so the viewer sees which configuration matches which split.
  Work done as get_area under a force-displacement graph.
- Momentum: before/after panels with velocity arrows proportional to speed and
  masses as differently-sized shapes; the summed momentum arrow must be
  IDENTICAL before and after — that identity is the point. Elastic vs inelastic
  shows in whether the kinetic-energy bars still match.
- Circular motion: MoveAlongPath around a Circle with the centripetal arrow
  ALWAYS to the centre and velocity ALWAYS tangential (draw the radius and mark
  the RightAngle). Never draw an outward "centrifugal" force in an inertial
  frame. Removing the force sends the object along the tangent.
- SHM: acceleration points BACK toward equilibrium and grows with displacement
  — a restoring-force arrow that flips side to side and is longest at maximum
  displacement. The strongest visual is COUPLED CONTINUOUS MOTION: one
  ValueTracker (phase or time) drives BOTH the oscillator's position AND the
  point on the displacement-time sine beside it, so the mass and the graph move
  in genuine lockstep and the curve is generated by the motion (the verified
  CONTROLLED CONTINUOUS MOTION mechanism-with-coupled-effect pattern; keep it
  ~3s and let geometry, not per-frame Text, carry any value). A discrete Dot
  tracing an already-drawn sine is an acceptable fallback when reliability
  matters more. KE and PE bars swap while their sum holds. Damping as a
  decreasing-amplitude envelope."""

_WAVES = """WAVES
- A plotted sine where amplitude, wavelength, frequency and phase are
  measurable, LABELLED distances — a double-headed arrow spanning one
  wavelength beats the word "wavelength".
- A travelling wave should actually TRAVEL: one ValueTracker on phase driving an
  always_redraw sine so the waveform propagates continuously, rather than jumping
  between static frames (the verified CONTROLLED CONTINUOUS MOTION wave-phase
  pattern — keep it ~3s, one reactive plot). Superposition as two waves
  Transforming into their sum, or (stronger) two phase-driven waves plus their
  live sum so the reinforcement/cancellation is watched as the phases slide; a
  standing wave as fixed nodes with antinodes growing between them.
- Reflection, refraction, diffraction and interference as staged geometric
  constructions with correct angles and path differences.
- Distinguish transverse from longitudinal explicitly: longitudinal is a row of
  Dots bunching into compressions and spreading into rarefactions, NOT a
  transverse sine wave."""

_ELECTRICITY = """ELECTRICITY & CIRCUITS
- Current as charge carriers (Dots) drifting along a conductor at a rate that
  visibly matches the current; potential difference as an energy drop across a
  component; resistance as an impediment that slows the carriers.
- I-V characteristics on Axes: straight for an ohmic conductor, curved for a
  filament lamp or diode — the SHAPE is the physics.
- Circuits as clean node-and-edge diagrams from straight Lines with
  right-angled corners and labelled components; show the path with animated
  Dots or ShowPassingFlash along the wires. Series: the SAME current
  everywhere, p.d.s adding. Parallel: the SAME p.d. across branches, current
  splitting — animate the split at the junction. Show a change (a switch
  closing, a resistor added) by re-animating the flow, not by relabelling.
- Capacitors: charge accumulating on two plates while the charging current
  DECREASES, with the exponential charge/discharge curve on Axes and the time
  constant marked as a specific interval; stored energy as get_area under a
  charge-voltage plot.
- Electric fields: radial lines OUT of positive and INTO negative charge, with
  arrowheads and correct symmetry; a uniform field between parallel plates as
  evenly spaced parallel arrows. Field lines never cross and never start or end
  in empty space. A test charge's force is tangent to a field line;
  equipotentials run perpendicular to the field lines."""

_MAGNETISM = """MAGNETISM & ELECTROMAGNETIC INDUCTION
- Use the standard page convention: OUT of the page is a Circle with a Dot at
  its centre; INTO the page is a Circle with Cross(Circle(...)) through it.
- The field around a straight current-carrying wire is concentric Circles with
  the correct sense; a bar magnet's field loops from N to S.
- The motor effect involves three mutually perpendicular directions (current,
  field, force) — draw them with explicit RightAngle marks and get the
  handedness right; a reversed force is a physics error.
- Induction is driven by CHANGING flux, so the animation must show something
  changing — a magnet entering a coil, an area shrinking, a field
  strengthening. The induced current appears only WHILE the change happens and
  stops when it stops. Lenz's law means the induced effect visibly OPPOSES the
  change that caused it; do not imply the effect precedes or causes its own
  driver."""

_OPTICS = """OPTICS
- Ray diagrams with straight rays and correct angles measured from the NORMAL —
  draw the normal as a DashedLine and mark the angles with Angle.
- Refraction bends toward the normal entering a denser medium; total internal
  reflection occurs only past the critical angle and only going into a less
  dense medium.
- Lens and mirror images built from the standard principal rays, with the image
  located where the rays actually meet (or appear to)."""

_THERMAL = """THERMAL PHYSICS
- Particles as Dots whose speed and spacing represent temperature and state;
  heating as faster motion.
- A change of state is a change in ordering/spacing at CONSTANT temperature —
  pair it with a temperature-time graph showing the flat plateau, because the
  plateau is the insight.
- Gas laws as a pressure-volume plot on Axes with a piston Rectangle changing
  size alongside, so the graph and the apparatus move together.
- Energy transfer as a directional flow between labelled regions."""

_QUANTUM_NUCLEAR = """QUANTUM, PARTICLE & NUCLEAR PHYSICS
- A photon is a DISCRETE packet (a small marked object or short wavy Line),
  never a continuous stream — the quantisation is the point. Atomic energy
  levels as UNEQUALLY spaced horizontal Lines with an electron Dot jumping
  between them, emitting or absorbing a photon whose colour matches the gap;
  the line spectrum is thin coloured Rectangles at positions set by those gaps.
- Photoelectric effect: electrons are released only ABOVE a threshold
  frequency — show a below-threshold photon producing nothing however many
  arrive, since that failure is the evidence.
- Standard model structure as a grouped grid of labelled Dots/Circles with
  colour marking the family; a hadron as its quarks inside a containing shape
  (three for a baryon, a quark-antiquark pair for a meson).
- Interactions as a Feynman-style diagram: straight Lines meeting at a vertex
  Dot, a distinctly styled (wavy/dashed) exchange boson between vertices, and
  time running consistently in ONE direction. Tally charge, baryon and lepton
  number on each side to show conservation.
- Nuclei as clustered Dots in two colours. Alpha decay as a two-proton
  two-neutron cluster leaving; beta-minus as a neutron becoming a proton with
  an electron emitted; gamma as an energy-level drop.
- Radioactive decay as an exponential curve with successive half-lives marked
  as EQUAL x intervals each halving y (get_vertical_line at each) — the equal
  spacing IS the concept. Binding energy per nucleon as the curve peaking near
  iron, with fission on the heavy side and fusion on the light side both moving
  TOWARD the peak."""

_ASTROPHYSICS = """ASTROPHYSICS & GRAVITATION
- Orbits as an ellipse or circle traced by MoveAlongPath with the central body
  at a FOCUS (not the centre) — faster near periapsis when Kepler's second law
  is the point, with equal-area sweeps as shaded Sectors/Polygons.
- Gravitational fields are radial and INWARD, always attractive: there is no
  repulsive case and drawing one is a physics error. The parallel with the
  electric field (both radial, both inverse-square) is worth drawing, but state
  the contrast — gravity has one sign, charge has two.
- Hertzsprung-Russell diagrams as a scatter of Dots on Axes with the main
  sequence a visible diagonal band; the temperature axis is conventionally
  REVERSED.
- Redshift as thin Rectangle spectral lines keeping their relative spacing
  while shifting bodily toward the red end — the preserved pattern is what
  identifies the shift.
- Inverse-square dimming as the same light spread over a growing area; parallax
  as a nearby star apparently shifting against fixed background Dots as the
  observation point moves.
- A gravitational "potential well" is a metaphor: do not let it imply the well
  is a physical surface."""

_GENERAL = """GENERAL SCENE (no single specialist domain applies — this is NOT permission
for a thinner or less-considered scene; it means invent the metaphor rather than
borrow one, and it deserves the SAME visual effort as any domain scene):
- This scene is an introduction, a recap, a framing question, a transition, or
  otherwise not tied to one technical domain. Build the visual from the
  lesson's PURPOSE — comparison, process, cause and effect, structure,
  hierarchy, quantity, transformation — using the core visual-storytelling
  rules already given, not a placeholder title card.
- Do not invent domain notation, axes, field lines or equations the scene does
  not actually need, and do not reach for a specialist diagram to look rigorous.
- REACH FOR DEPTH WHEN IT HELPS: general scenes (comparisons, overviews,
  before/after framing) are exactly where 2.5D layering — set_z_index, scale,
  opacity — often clarifies structure. Consider whether stacking, nesting, or
  a foreground/background split would make this scene's idea clearer before
  defaulting to a flat single-layer composition. See LIFT INTO DEPTH above.
- BUILD ONE STRONG BESPOKE VISUAL, not a generic box-and-arrow diagram: a
  process as parts assembling or flowing; a comparison as two arrangements
  transforming into each other or standing side by side with a shared visual
  language; cause-and-effect as one change visibly producing another; a
  hierarchy as a structure that grows, nests, or ranks by size/position; a
  quantity as something filling, splitting, or scaling proportionally.
- USE THE FULL TOOLKIT even without a domain to anchor it: TransformFromCopy
  for a derivation-like progression, LaggedStart for parts of a whole arriving
  in order, a short ArcBetweenPoints move for something transferring or
  flowing, dim-the-rest to focus attention on one element among several. A
  general scene is where inventing a fresh, concrete metaphor matters MOST —
  there is no formula to fall back on, so make the metaphor specific and
  visual rather than abstract and textual."""


_A_LEVEL_MATH_MODULES = {
    "algebra_functions": """ALGEBRA & FUNCTIONS
- Keep each manipulation anchored to the expression it came from. Use
  TransformFromCopy for substitution and rearrangement, with stable colors for
  the same term across every line.
- For composite and inverse functions, animate values through an input-machine-
  output chain; reverse the arrows for the inverse and state domain restrictions.
- For equations and inequalities, verify candidate roots and show excluded
  values or sign intervals explicitly. Do not present algebra as unexplained
  symbol replacement.""",
    "graphs": """GRAPHS
- Build axes first with meaningful ranges, then reveal intercepts, turning
  points and asymptotes before interpreting the curve.
- Show transformations by transforming the persistent curve while a parameter
  changes; keep the parent graph dimly visible for comparison.
- Use axes.c2p and axes.i2gp for every point. A graph must encode scale, domain,
  range and discontinuities accurately, not merely look curve-like.""",
    "coordinate_geometry": """COORDINATE GEOMETRY
- Derive gradient from a visible rise/run triangle and connect it to the
  coefficients in the line equation.
- For circles, show center and radius geometrically before using the equation.
  A tangent touches at one point and is perpendicular to the radius there.
- For intersections, animate the same point satisfying both loci; distinguish
  exact coordinates from visually estimated ones.""",
    "sequences_series": """SEQUENCES & SERIES
- Build recurrence terms from the preceding term and place nth-term values on a
  number line or graph so convergence, oscillation or divergence is visible.
- Show partial sums as an accumulator. For a geometric series, make the common
  ratio visible and state that an infinite sum requires abs(r) < 1.
- Preserve the distinction between a sequence of terms and its series of
  accumulated sums.""",
    "trigonometry": """TRIGONOMETRY
- Use radians for calculus and graph motion. Link a unit-circle angle,
  projection and graph point with one shared tracker.
- When solving in an interval, mark every graph intersection and map solutions
  to quadrants; never stop at the calculator's principal value.
- For identities, transform matching terms while keeping both sides visible.
  For sine/cosine rule problems, highlight the known side-angle structure that
  justifies the selected rule before showing its name.""",
    "exponentials_logarithms": """EXPONENTIALS & LOGARITHMS
- Show constant multiplicative change over equal x-intervals. Distinguish
  growth, decay, doubling time and half-life visually.
- Present logarithms as inverse functions by reflecting the exponential in
  y=x; show x > 0 as the logarithm's domain and the vertical asymptote.
- When linearising data, transform the curved relationship into the correctly
  relabelled straight-line graph and connect gradient/intercept to parameters.""",
    "differentiation": """DIFFERENTIATION
- Connect f, its moving tangent gradient and f' on aligned axes. Stationary
  points of f must line up with roots of f'.
- Make product, quotient and chain rules preserve the dependency structure;
  do not show a memorised rule without identifying inner and outer functions.
- For optimization, define the model and valid domain, solve for stationary
  candidates, classify them, and interpret the answer in context.""",
    "integration": """INTEGRATION
- Treat definite integration as signed accumulation: areas below the axis are
  negative. Show bounds moving on the same axes as the shaded region.
- Show an indefinite integral with its constant of integration and explain it
  as a family of vertical translations.
- Refine Riemann rectangles or trapezia toward the area; for substitution,
  transform the integrand, differential and limits together.""",
    "numerical_methods": """NUMERICAL METHODS
- For change-of-sign root location, mark the interval endpoints and show the
  function values with opposite signs; do not claim this proves uniqueness.
- For fixed-point iteration, use the cobweb between y=g(x) and y=x and show
  convergence or divergence from the geometry.
- For Newton-Raphson, draw each tangent and its next x-axis intercept. State the
  starting value, stopping criterion and an appropriate error bound.""",
    "vectors": """VECTORS
- Draw vectors as directed arrows with components tied to the axes. Addition is
  tip-to-tail; scalar multiplication changes magnitude and possibly direction.
- For vector equations of lines, distinguish the position vector from the
  direction vector and animate the parameter moving a point along the line.
- At intersections, show the same point satisfying both parameterizations.
  Do not imply skew 3D lines intersect merely because of a 2D projection.""",
    "statistics": """STATISTICS
- Keep sample, population, parameter and statistic visibly distinct. State the
  sampling method and expose likely sources of bias.
- Match the display to the variable: separated bars for discrete distributions,
  a continuous density curve for normal models, and proportional histogram
  area when class widths differ.
- For hypothesis tests, show H0/H1, tail direction, significance level and the
  test statistic against the critical region. Interpret in context and never
  equate correlation with causation.""",
}

_missing_a_level = sorted(set(A_LEVEL_MATH_TOPICS) - set(_A_LEVEL_MATH_MODULES))
if _missing_a_level:  # pragma: no cover
    raise RuntimeError(
        f"A-level mathematics topics without guidance: {_missing_a_level}"
    )


def build_a_level_math_section(topic: Optional[str]) -> str:
    """Return exact syllabus guidance without adding unrelated maths modules."""
    if not isinstance(topic, str):
        return ""
    key = topic.strip().lower().replace("-", "_").replace(" ", "_")
    module = _A_LEVEL_MATH_MODULES.get(key)
    if not module:
        return ""
    return f"A-LEVEL MATHEMATICS FOCUS (THIS scene only):\n{module}"


def a_level_math_menu_for_prompt() -> str:
    """Controlled syllabus-topic menu used by the storyboard director."""
    labels = {
        "algebra_functions": "Algebra & Functions",
        "graphs": "Graphs",
        "coordinate_geometry": "Coordinate Geometry",
        "sequences_series": "Sequences & Series",
        "trigonometry": "Trigonometry",
        "exponentials_logarithms": "Exponentials & Logarithms",
        "differentiation": "Differentiation",
        "integration": "Integration",
        "numerical_methods": "Numerical Methods",
        "vectors": "Vectors",
        "statistics": "Statistics",
    }
    return "\n".join(f"  - {key}: {labels[key]}" for key in A_LEVEL_MATH_TOPICS)


_MODULES = {
    "general": _GENERAL,
    "algebra": _ALGEBRA,
    "geometry": _GEOMETRY,
    "linear_algebra": _LINEAR_ALGEBRA,
    "calculus": _CALCULUS,
    "probability_statistics": _PROBABILITY_STATISTICS,
    "discrete_algorithms": _DISCRETE_ALGORITHMS,
    "mechanics": _MECHANICS,
    "waves": _WAVES,
    "electricity": _ELECTRICITY,
    "magnetism": _MAGNETISM,
    "optics": _OPTICS,
    "thermal": _THERMAL,
    "quantum_nuclear": _QUANTUM_NUCLEAR,
    "astrophysics": _ASTROPHYSICS,
}

# Fail loudly at import if the taxonomy and the modules ever drift apart.
_missing = sorted(set(DOMAIN_TAGS) - set(_MODULES))
if _missing:  # pragma: no cover - guards a developer mistake, not runtime input
    raise RuntimeError(f"domain tags without a guidance module: {_missing}")


def known_tags() -> Sequence[str]:
    """The controlled taxonomy, in canonical order."""
    return DOMAIN_TAGS


_TAG_ALIASES = {
    # Geometry & Trigonometry
    "trigonometry": "geometry",
    "trig": "geometry",
    "triangles": "geometry",
    "vector_geometry": "geometry",
    # Probability & Statistics
    "stats": "probability_statistics",
    "probability": "probability_statistics",
    "statistics": "probability_statistics",
    # Calculus
    "diff_eq": "calculus",
    "differential_equations": "calculus",
    "integration": "calculus",
    "derivatives": "calculus",
    "differentiation": "calculus",
    # Discrete & Algorithms
    "binary_search": "discrete_algorithms",
    "algorithms": "discrete_algorithms",
    "algorithm": "discrete_algorithms",
    "sorting": "discrete_algorithms",
    "dsa": "discrete_algorithms",
    "array": "discrete_algorithms",
    "arrays": "discrete_algorithms",
    "two_pointers": "discrete_algorithms",
    "two_pointer": "discrete_algorithms",
    "hashing": "discrete_algorithms",
    "hash_map": "discrete_algorithms",
    "hash_set": "discrete_algorithms",
    "prefix_sum": "discrete_algorithms",
    "matrix_traversal": "discrete_algorithms",
    "sliding_window": "discrete_algorithms",
    "kadane": "discrete_algorithms",
    "kadanes_algorithm": "discrete_algorithms",
    "intervals": "discrete_algorithms",
    "interval_merge": "discrete_algorithms",
    "greedy": "discrete_algorithms",
    "greedy_array": "discrete_algorithms",
    # Mechanics
    "shm": "mechanics",
    "harmonic_motion": "mechanics",
    # Waves
    "standing_waves": "waves",
    "superposition": "waves",
    # Electricity
    "circuits": "electricity",
    "circuit": "electricity",
    # Magnetism
    "induction": "magnetism",
    "electromagnetic_induction": "magnetism",
    # Optics
    "refraction": "optics",
    "lenses": "optics",
    # Quantum & Nuclear
    "energy_levels": "quantum_nuclear",
    "spectra": "quantum_nuclear",
    "photons": "quantum_nuclear",
}


def normalize_tags(tags: Optional[Iterable[str]]) -> List[str]:
    """Filter to known tags, de-duplicate (first wins), and bound the count.

    Defensive: routing must never crash scene generation. Unknown tags are
    mapped via aliases or rejected at the schema boundary; anything odd that
    reaches here is dropped and the safe "general" default applies.
    """
    out: List[str] = []
    for tag in tags or ():
        if not isinstance(tag, str):
            continue
        key = tag.strip().lower().replace("-", "_").replace(" ", "_")
        key = _TAG_ALIASES.get(key, key)
        if key in _MODULES and key not in out:
            out.append(key)
    if not out:
        return ["general"]
    # A specialist tag makes a co-selected "general" meaningless.
    if len(out) > 1:
        out = [t for t in out if t != "general"] or ["general"]
    return out[:MAX_TOTAL_DOMAIN_TAGS]


def modules_for(tags: Optional[Iterable[str]]) -> List[str]:
    """Return the selected tags (normalized) — the audit view of routing."""
    return normalize_tags(tags)


def build_domain_section(tags: Optional[Iterable[str]]) -> str:
    """Assemble the domain guidance block for the selected tags only.

    A bare "general" scene gets the short general module without the accuracy
    preamble (it makes no domain claims); any specialist scene gets the
    accuracy rule plus its 1-3 modules, primary first.
    """
    selected = normalize_tags(tags)
    if selected == ["general"]:
        return f"{_DOMAIN_HEADER}\n\n{_GENERAL}"
    body = "\n\n".join(_MODULES[t] for t in selected)
    return f"{_DOMAIN_HEADER}\n\n{_ACCURACY_RULE}\n\n{body}"


def tag_menu_for_prompt() -> str:
    """The taxonomy rendered for the storyboard prompt (one line per tag)."""
    descriptions = {
        "general": "intros, recaps, framing questions, non-specialist scenes",
        "algebra": "expressions, functions, graph transformations, exponentials/logs, sequences & series",
        "geometry": "coordinate geometry, circles, triangles, trigonometry, angles",
        "linear_algebra": "vectors, vector geometry, matrices, transformations, determinants, eigenvectors",
        "calculus": "limits, differentiation, integration, area/accumulation, numerical methods",
        "probability_statistics": "probability, distributions, sampling, hypothesis testing, data displays",
        "discrete_algorithms": "sets, logic, graphs/networks, algorithms, recursion",
        "mechanics": "kinematics, forces, moments, energy, momentum, circular motion, SHM",
        "waves": "wave properties, superposition, standing waves, interference, sound",
        "electricity": "current, voltage, resistance, circuits, capacitors, electric fields",
        "magnetism": "magnetic fields, motor effect, electromagnetic induction",
        "optics": "reflection, refraction, lenses, mirrors, ray diagrams",
        "thermal": "temperature, heat transfer, changes of state, gas laws",
        "quantum_nuclear": "photons, energy levels, particle physics, radioactivity, nuclear energy",
        "astrophysics": "orbits, gravitation, stars, cosmology, redshift",
    }
    return "\n".join(f"  - {t}: {descriptions[t]}" for t in DOMAIN_TAGS)
